/**
 * Generate `supabase/migrations/0003_seed.sql` from the artefacts the
 * application already holds.
 *
 *     npx tsx scripts/build-seed.ts
 *
 * There is exactly one source for each thing, and this script reads it rather
 * than restating it:
 *
 *   zones, divisions, officers   lib/railways.ts and lib/roles.ts
 *   stations                     public/data/stations.json
 *   sections, plan, blocks, kpis public/data/plan.json
 *
 * Restating any of them here would recreate the duplication bug that has bitten
 * this project three times - a table written twice and kept in step by hand.
 *
 * The output is a migration rather than a one-off insert: it is idempotent, so
 * re-running it after a re-solve replaces the plan instead of accumulating
 * copies.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import { REFERENCE_DIVISION, REFERENCE_ZONE, ZONES } from "../lib/railways";
import { ROLES } from "../lib/roles";
import { planReference } from "../lib/plan";

const ROOT = path.resolve(__dirname, "..");
const MIG = path.resolve(ROOT, "..", "supabase", "migrations");
const OUT_ORG = path.resolve(MIG, "0003_seed_org.sql");
const OUT_STATIONS = path.resolve(MIG, "0003b_seed_stations.sql");
const OUT_PLAN = path.resolve(MIG, "0004_seed_plan.sql");

/** Single-quote escaping for SQL literals. */
function q(v: string | null | undefined): string {
  if (v === null || v === undefined) return "null";
  return `'${v.replace(/'/g, "''")}'`;
}
function n(v: number | null | undefined): string {
  return v === null || v === undefined || Number.isNaN(v) ? "null" : String(v);
}

const HEAD = (what: string) => [
  `-- Corridor - ${what}. GENERATED by web/scripts/build-seed.ts; do not edit.`,
  "-- Idempotent: re-running replaces rather than duplicates.",
  "",
  "begin;",
  "",
];

//  Reference data - the Ministry list and the station master. Published
//  facts that change when the Ministry changes them, not when we re-solve.
//  Zones, divisions and officers: a few hundred rows, small enough to paste
//  into the Supabase SQL editor by hand.
const out: string[] = HEAD("organisation seed");
//  8,697 stations. Kept separate because 2 MB will not go through the SQL
//  editor, and because nothing but the /network page needs it.
const stationsOut: string[] = HEAD("station master seed");
//  The plan - rewritten on every solve, which is why it is a separate file.
const planOut: string[] = HEAD("plan seed");

// --- zones and divisions ----------------------------------------------------
out.push("-- Ministry of Railways list: 17 zones, 68 divisions.");
for (const z of ZONES) {
  out.push(
    `insert into zones (code, name, hq, year) values (${q(z.code)}, ${q(z.name)}, ${q(z.hq)}, ${z.year})` +
      ` on conflict (code) do update set name = excluded.name, hq = excluded.hq, year = excluded.year;`,
  );
}
out.push("");
for (const z of ZONES) {
  for (const d of z.divisions) {
    out.push(
      `insert into divisions (code, zone_code, name) values (${q(d.code)}, ${q(z.code)}, ${q(d.name)})` +
        ` on conflict (zone_code, code) do update set name = excluded.name;`,
    );
  }
}

// --- officers ---------------------------------------------------------------
out.push("", `-- ${ROLES.length} posts: five per division, five per zone.`);
for (const r of ROLES) {
  const post = r.userId.split("/")[0];
  out.push(
    `insert into officers (id, post, designation, full_name, level, zone_code, division_code, department, remit) values (` +
      `${q(r.userId)}, ${q(post)}, ${q(r.designation)}, ${q(r.full)}, ${q(r.level)}::post_level, ` +
      `${q(r.zone.code)}, ${q(r.division?.code ?? null)}, ` +
      `${r.department ? `${q(r.department)}::department` : "null"}, ${q(r.remit)})` +
      ` on conflict (id) do update set designation = excluded.designation, remit = excluded.remit;`,
  );
}

// --- stations ---------------------------------------------------------------
interface StationRow {
  c: string;
  n: string;
  z: string | null;
  s: string | null;
  lat: number;
  lon: number;
}
const stations = JSON.parse(
  readFileSync(path.join(ROOT, "public", "data", "stations.json"), "utf-8"),
) as { rows: StationRow[] };
const zoneCodes = new Set(ZONES.map((z) => z.code));
stationsOut.push("", `-- ${stations.rows.length} stations (DataMeet, CC0).`);
for (const s of stations.rows) {
  //  Zone is a foreign key, so a code the Ministry list does not carry (KR,
  //  Konkan, is a PSU rather than one of the 17) is stored as null.
  const zone = s.z && zoneCodes.has(s.z) ? q(s.z) : "null";
  stationsOut.push(
    `insert into stations (code, name, zone_code, state, lat, lon) values (${q(s.c)}, ${q(s.n)}, ${zone}, ${q(s.s)}, ${n(s.lat)}, ${n(s.lon)})` +
      ` on conflict (code) do update set name = excluded.name, zone_code = excluded.zone_code;`,
  );
}

// --- the plan ---------------------------------------------------------------
type Variant = "optimised" | "baseline";
interface Plan {
  generatedAt?: string;
  provenance: { seed?: number };
  horizon: { days: number };
  sections: { id: string; name: string; kmFrom: number; kmTo: number }[];
  protectedPaths?: {
    train: string;
    name: string;
    from: string;
    to: string;
    daysPerWeek: number;
  }[];
  solver?: { status?: string; objective?: number; bound?: number };
  placement?: { objective?: number; bound?: number };
  kpis: Record<Variant, Record<string, number>>;
  optimised: PlanSide;
  baseline: PlanSide;
}
interface PlanSide {
  blocks: {
    id: string;
    section: string;
    scope: string;
    day: number;
    startSlot: number;
    durSlots: number;
    startHHMM: string;
    endHHMM: string;
    detentionMinutes: number;
    clubbed: boolean;
    departments: string[];
  }[];
  tasks: {
    id: string;
    department: string;
    section: string;
    activity: string;
    criticality: string;
    scheduled: boolean;
    blockId: string | null;
    startSlot: number | null;
    riskRate: number;
  }[];
}
const plan = JSON.parse(
  readFileSync(path.join(ROOT, "public", "data", "plan.json"), "utf-8"),
) as Plan;

//  Built by the same function the browser uses, so a row and the artefact
//  it carries cannot be given different names.
const REF = planReference(plan);
//  The division the artefact belongs to. Imported, not typed: usePlan's
//  offline scoping reads the same two constants, and a seed that wrote the
//  plan against one division while the app scoped it to another would be
//  the write-it-twice bug again.
const ZONE = REFERENCE_ZONE;
const DIV = REFERENCE_DIVISION;

planOut.push("", "-- Sections: geometry derived from published station coordinates.");
for (const s of plan.sections) {
  planOut.push(
    `insert into sections (id, division_code, zone_code, name, km_from, km_to) values (${q(s.id)}, ${q(DIV)}, ${q(ZONE)}, ${q(s.name)}, ${s.kmFrom}, ${s.kmTo})` +
      ` on conflict (id) do update set name = excluded.name, km_from = excluded.km_from, km_to = excluded.km_to;`,
  );
}

planOut.push(
  "",
  "-- The plan. A re-solve supersedes; it does not accumulate.",
  "--",
  "-- This comment used to say that while the code deleted only rows carrying",
  "-- THIS reference - and the reference contains the generation date, so a",
  "-- re-solve on another day left the previous plan sitting beside the new one",
  "-- and the division held two current plans. Found when a rebuilt artefact",
  "-- was seeded and the screen went on showing the older payload.",
  "--",
  "-- Prior plans for this division are marked superseded rather than deleted:",
  "-- the status enum carries that value for exactly this, and the audit log",
  "-- references plan ids, so deleting them would orphan the record of who",
  "-- submitted and approved what. Only the identical reference is replaced,",
  "-- which keeps re-running this file idempotent.",
  `update plans set status = 'superseded'`,
  `  where division_code = ${q(DIV)} and reference <> ${q(REF)}`,
  `    and status <> 'superseded';`,
  `delete from plans where reference = ${q(REF)};`,
  `insert into plans (reference, zone_code, division_code, horizon_days, seed, status,`,
  `  solver_status, objective, bound, placement_objective, placement_bound, generated_at, payload)`,
  `values (${q(REF)}, ${q(ZONE)}, ${q(DIV)}, ${plan.horizon.days}, ${n(plan.provenance.seed)}, 'draft',`,
  `  ${q(plan.solver?.status ?? null)}, ${n(plan.solver?.objective)}, ${n(plan.solver?.bound)},`,
  //  The artefact itself, so the tables and the screen cannot disagree: both
  //  are written here, in one transaction, from this one file.
  `  ${n(plan.placement?.objective)}, ${n(plan.placement?.bound)}, ${q(plan.generatedAt ?? new Date().toISOString())},`,
  `  ${q(JSON.stringify(plan))}::jsonb);`,
  "",
  `create temporary table _p as select id from plans where reference = ${q(REF)};`,
);

for (const variant of ["optimised", "baseline"] as Variant[]) {
  const side = plan[variant];
  planOut.push("", `-- ${variant}: ${side.blocks.length} blocks, ${side.tasks.length} tasks`);
  for (const b of side.blocks) {
    const depts = `array[${b.departments.map((d) => `${q(d)}::department`).join(",")}]`;
    planOut.push(
      `insert into blocks (id, plan_id, variant, section_id, scope, day, start_slot, dur_slots, start_hhmm, end_hhmm, detention_min, clubbed, departments)` +
        ` select ${q(b.id)}, id, ${q(variant)}, ${q(b.section)}, ${q(b.scope)}::block_scope, ${b.day}, ${b.startSlot}, ${b.durSlots}, ${q(b.startHHMM)}, ${q(b.endHHMM)}, ${b.detentionMinutes}, ${b.clubbed}, ${depts} from _p;`,
    );
  }
  for (const t of side.tasks) {
    planOut.push(
      `insert into tasks (id, plan_id, variant, department, section_id, activity, criticality, scheduled, block_id, start_slot, risk_rate)` +
        ` select ${q(t.id)}, id, ${q(variant)}, ${q(t.department)}::department, ${q(t.section)}, ${q(t.activity)}, ${q(t.criticality)}::criticality, ${t.scheduled}, ${q(t.blockId)}, ${n(t.startSlot)}, ${t.riskRate} from _p;`,
    );
  }
  const k = plan.kpis[variant];
  planOut.push(
    `insert into kpis (plan_id, variant, blocks, block_hours, detention_minutes, detention_per_task, risk_carried, scheduled, statutory_done, statutory_total, multidept_pct, packing)` +
      ` select id, ${q(variant)}, ${k.blocks}, ${k.block_hours}, ${k.detention_minutes}, ${k.detention_per_task}, ${k.risk_carried}, ${k.scheduled}, ${k.statutory_done}, ${k.statutory_total}, ${k.multidept_pct}, ${k.packing} from _p;`,
  );
}

for (const p of plan.protectedPaths ?? []) {
  const toMin = (hhmm: string) => {
    const [h, m] = hhmm.split(":").map(Number);
    return h * 60 + m;
  };
  planOut.push(
    `insert into protected_paths (plan_id, train, name, entry_min, exit_min, days_per_week)` +
      ` select id, ${q(p.train)}, ${q(p.name)}, ${toMin(p.from)}, ${toMin(p.to)}, ${p.daysPerWeek} from _p;`,
  );
}

planOut.push("", "drop table _p;", "commit;", "");
out.push("", "commit;", "");

mkdirSync(MIG, { recursive: true });
const NL = "\n";
stationsOut.push("", "commit;", "");
writeFileSync(OUT_ORG, out.join(NL), "utf-8");
writeFileSync(OUT_STATIONS, stationsOut.join(NL), "utf-8");
writeFileSync(OUT_PLAN, planOut.join(NL), "utf-8");
const kb = (b: string[]) => (Buffer.byteLength(b.join(NL)) / 1024).toFixed(0);
console.log(`org        0003_seed_org.sql       (${kb(out)} KB)`);
console.log(`stations   0003b_seed_stations.sql (${kb(stationsOut)} KB)`);
console.log(
  `  ${ZONES.length} zones · ${ZONES.reduce((a, z) => a + z.divisions.length, 0)} divisions · ` +
    `${ROLES.length} officers · ${stations.rows.length} stations`,
);
console.log(`plan       0004_seed_plan.sql  (${kb(planOut)} KB)`);
console.log(
  `  ${REF}: ${plan.optimised.blocks.length} optimised blocks, ${plan.baseline.blocks.length} baseline, ` +
    `${(plan.protectedPaths ?? []).length} protected paths`,
);
